# Big Data File Formats

## Parquet

### Convert To Parquet (Pandas)

In [4]:
import pandas as pd

df = pd.read_csv('files/equities.csv')

print(df.head())

df.to_parquet('files/equities.parquet')

      symbol                              name  \
0  000002.SZ             China Vanke Co., Ltd.
1  000004.SZ                               two
2  000005.SZ     Shenzhen Fountain Corporation
3  000006.SZ  Shenzhen Zhenye (Group) Co.,Ltd.
4  000007.SZ     Shenzhen Quanxinhao Co., Ltd.

                                             summary currency  \
0  China Vanke Co., Ltd., together with its subsi...      CNY
1  two is a blank check company. The company was ...      CNY
2  Shenzhen Fountain Corporation engages in real ...      CNY
3  Shenzhen Zhenye (Group) Co.,Ltd. engages in th...      CNY
4  Shenzhen Quanxinhao Co., Ltd. owns and operate...      CNY

                   sector          industry_group  \
0             Real Estate             Real Estate
1              Financials  Diversified Financials
2             Real Estate             Real Estate
3             Real Estate             Real Estate
4  Consumer Discretionary       Consumer Services

                               industry exchange                   market  \
0  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
1        Diversified Financial Services      SHZ  Shenzhen Stock Exchange
2  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
3  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
4         Hotels, Restaurants & Leisure      SHZ  Shenzhen Stock Exchange

         country state           city zipcode                     website  \
0          China   NaN       Shenzhen  518083        http://www.vanke.com
1  United States    CA  San Francisco   94129      http://www.sz000004.cn
2          China   NaN       Shenzhen  518001  http://www.fountain.com.cn
3          China   NaN       Shenzhen  518008       http://www.zhenye.com
4          China   NaN       Shenzhen  518031     http://www.sz000007.com

  market_cap          isin cusip figi composite_figi shareclass_figi
0  Large Cap  CNE100001SR9   NaN  NaN            NaN             NaN
1  Micro Cap           NaN   NaN  NaN            NaN             NaN
2  Small Cap  CNE0000001L7   NaN  NaN            NaN             NaN
3  Small Cap  CNE000000164   NaN  NaN            NaN             NaN
4  Micro Cap  CNE0000000P0   NaN  NaN            NaN             NaN

### Convert to Parquet (Pyarrow)

In [6]:
import pyarrow.csv as pv
import pyarrow.parquet as pq

file_location = "files/equities.csv"

table = pv.read_csv(file_location)
pq.write_table(table, "files/equities-2.parquet")

### Read Metadata

In [7]:
from pyarrow import parquet as pq

file_info = pq.ParquetFile("files/equities-2.parquet")
print("--- METADATA ---")
print(file_info.metadata)
print("")
print(file_info.schema)

--- METADATA ---
<pyarrow._parquet.FileMetaData object at 0x10db3ae80>
  created_by: parquet-cpp-arrow version 14.0.1
  num_columns: 20
  num_rows: 158647
  num_row_groups: 1
  format_version: 2.6
  serialized_size: 4318

<pyarrow._parquet.ParquetSchema object at 0x12647f240>
required group field_id=-1 schema {
  optional binary field_id=-1 symbol (String);
  optional binary field_id=-1 name (String);
  optional binary field_id=-1 summary (String);
  optional binary field_id=-1 currency (String);
  optional binary field_id=-1 sector (String);
  optional binary field_id=-1 industry_group (String);
  optional binary field_id=-1 industry (String);
  optional binary field_id=-1 exchange (String);
  optional binary field_id=-1 market (String);
  optional binary field_id=-1 country (String);
  optional binary field_id=-1 state (String);
  optional binary field_id=-1 city (String);
  optional binary field_id=-1 zipcode (String);
  optional binary field_id=-1 website (String);
  optional binary field_id=-1 market_cap (String);
  optional binary field_id=-1 isin (String);
  optional binary field_id=-1 cusip (String);
  optional binary field_id=-1 figi (String);
  optional binary field_id=-1 composite_figi (String);
  optional binary field_id=-1 shareclass_figi (String);
}

### Parking Violations - Create Parquet

In [19]:
import pandas as pd

dtype_dict = {18: str, 29: str, 38: str, 40: str, 41: str, 42: str}

df = pd.read_csv(
    "files/Parking_Violations_Issued_-_Fiscal_Year_2015.csv",
    dtype=dtype_dict,
    parse_dates=["Issue Date"],
)

print(df.head())
print(df.dtypes)

df.to_parquet("files/Parking_Violations_Issued_-_Fiscal_Year_2015.parquet")

df

   Summons Number  Plate ID Registration State Plate Type Issue Date  \
0      8002531292   EPC5238                 NY        PAS 2014-10-01
1      8015318440    5298MD                 NY        COM 2015-03-06
2      7611181981   FYW2775                 NY        PAS 2014-07-28
3      7445908067   GWE1987                 NY        PAS 2015-04-13
4      7037692864  T671196C                 NY        PAS 2015-05-19

   Violation Code Vehicle Body Type Vehicle Make Issuing Agency  Street Code1  \
0              21              SUBN        CHEVR              T         20390
1              14               VAN        FRUEH              T         27790
2              46              SUBN        SUBAR              T          8130
3              19              4DSD        LEXUS              T         59990
4              19              4DSD        CHRYS              T         36090

   ...  Hydrant Violation  Double Parking Violation Latitude  Longitude  \
0  ...                NaN                       NaN      NaN        NaN
1  ...                NaN                       NaN      NaN        NaN
2  ...                NaN                       NaN      NaN        NaN
3  ...                NaN                       NaN      NaN        NaN
4  ...                NaN                       NaN      NaN        NaN

   Community Board  Community Council   Census Tract BIN BBL NTA
0              NaN                 NaN           NaN NaN NaN NaN
1              NaN                 NaN           NaN NaN NaN NaN
2              NaN                 NaN           NaN NaN NaN NaN
3              NaN                 NaN           NaN NaN NaN NaN
4              NaN                 NaN           NaN NaN NaN NaN

[5 rows x 51 columns]
Summons Number                                int64
Plate ID                                     object
Registration State                           object
Plate Type                                   object
Issue Date                           datetime64[ns]
Violation Code                                int64
Vehicle Body Type                            object
Vehicle Make                                 object
Issuing Agency                               object
Street Code1                                  int64
Street Code2                                  int64
Street Code3                                  int64
Vehicle Expiration Date                      object
Violation Location                          float64
Violation Precinct                            int64
Issuer Precinct                               int64
Issuer Code                                   int64
Issuer Command                               object
Issuer Squad                                 object
Violation Time                               object
Time First Observed                          object
Violation County                             object
Violation In Front Of Or Opposite            object
House Number                                 object
Street Name                                  object
Intersecting Street                          object
Date First Observed                          object
Law Section                                 float64
Sub Division                                 object
Violation Legal Code                         object
Days Parking In Effect                       object
From Hours In Effect                         object
To Hours In Effect                           object
Vehicle Color                                object
Unregistered Vehicle?                       float64
Vehicle Year                                float64
Meter Number                                 object
Feet From Curb                              float64
Violation Post Code                          object
Violation Description                        object
No Standing or Stopping Violation            object
Hydrant Violation                            object
Double Parking Violation                     object
Latitude                                    float64
Longitude                                   float64
Community Board                             float64
Community Council                           float64
Census Tract                                float64
BIN                                         float64
BBL                                         float64
NTA                                         float64
dtype: object

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Hydrant Violation,Double Parking Violation,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,8002531292,EPC5238,NY,PAS,2014-10-01,21,SUBN,CHEVR,T,20390,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8015318440,5298MD,NY,COM,2015-03-06,14,VAN,FRUEH,T,27790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7611181981,FYW2775,NY,PAS,2014-07-28,46,SUBN,SUBAR,T,8130,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7445908067,GWE1987,NY,PAS,2015-04-13,19,4DSD,LEXUS,T,59990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7037692864,T671196C,NY,PAS,2015-05-19,19,4DSD,CHRYS,T,36090,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11809228,8035170326,VCT8217,VA,PAS,2015-05-19,14,4DSD,HONDA,T,72830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11809229,8005276357,GHK4864,NY,PAS,2014-10-20,31,SUBN,ME/BE,T,34210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11809230,7155525273,T616724C,NY,OMT,2014-09-25,31,4DSD,LINCO,T,10610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11809231,8044311063,97720MD,NY,COM,2015-06-03,51,DUMP,PETER,T,10540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11809232,7684965852,73040KA,NY,COM,2015-06-16,69,VAN,FORD,T,34090,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Parking Violations - Query Parquet

In [28]:
import pandas as pd
from pyarrow import parquet as pq

file_location = "files/Parking_Violations_Issued_-_Fiscal_Year_2015.parquet"
file_info = pq.ParquetFile(file_location)

print(file_info.metadata)
print(file_info.schema)

df = pd.read_parquet(file_location, columns=["Issue Date", "Vehicle Make"])

print(df.head())

### GET TOTAL VIOLATIONS BY VEHICLE MAKE FOR MONTH OF JANUARY ###

# Filter for January 2015
jan_2015 = df[(df["Issue Date"] >= "2015-01-01") & (df["Issue Date"] < "2015-02-01")]

# Group by 'Vehicle Make' and count tickets
ticket_counts = jan_2015.groupby("Vehicle Make").size()

# Drop counts less than 100 (assuming this is bogus data)
ticket_counts = ticket_counts[ticket_counts >= 1000]

# The result is a Series with 'Vehicle Make' as the index and ticket counts as the values
ticket_counts

<pyarrow._parquet.FileMetaData object at 0x1263057b0>
  created_by: parquet-cpp-arrow version 14.0.1
  num_columns: 51
  num_rows: 11809233
  num_row_groups: 12
  format_version: 2.6
  serialized_size: 84344
<pyarrow._parquet.ParquetSchema object at 0x3e42e3b40>
required group field_id=-1 schema {
  optional int64 field_id=-1 Summons Number;
  optional binary field_id=-1 Plate ID (String);
  optional binary field_id=-1 Registration State (String);
  optional binary field_id=-1 Plate Type (String);
  optional int64 field_id=-1 Issue Date (Timestamp(isAdjustedToUTC=false, timeUnit=nanoseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional int64 field_id=-1 Violation Code;
  optional binary field_id=-1 Vehicle Body Type (String);
  optional binary field_id=-1 Vehicle Make (String);
  optional binary field_id=-1 Issuing Agency (String);
  optional int64 field_id=-1 Street Code1;
  optional int64 field_id=-1 Street Code2;
  optional int64 field_id=-1 Street Code3;
  optional binary field_id=-1 Vehicle Expiration Date (String);
  optional double field_id=-1 Violation Location;
  optional int64 field_id=-1 Violation Precinct;
  optional int64 field_id=-1 Issuer Precinct;
  optional int64 field_id=-1 Issuer Code;
  optional binary field_id=-1 Issuer Command (String);
  optional binary field_id=-1 Issuer Squad (String);
  optional binary field_id=-1 Violation Time (String);
  optional binary field_id=-1 Time First Observed (String);
  optional binary field_id=-1 Violation County (String);
  optional binary field_id=-1 Violation In Front Of Or Opposite (String);
  optional binary field_id=-1 House Number (String);
  optional binary field_id=-1 Street Name (String);
  optional binary field_id=-1 Intersecting Street (String);
  optional binary field_id=-1 Date First Observed (String);
  optional double field_id=-1 Law Section;
  optional binary field_id=-1 Sub Division (String);
  optional binary field_id=-1 Violation Legal Code (String);
  optional binary field_id=-1 Days Parking In Effect     (String);
  optional binary field_id=-1 From Hours In Effect (String);
  optional binary field_id=-1 To Hours In Effect (String);
  optional binary field_id=-1 Vehicle Color (String);
  optional double field_id=-1 Unregistered Vehicle?;
  optional double field_id=-1 Vehicle Year;
  optional binary field_id=-1 Meter Number (String);
  optional double field_id=-1 Feet From Curb;
  optional binary field_id=-1 Violation Post Code (String);
  optional binary field_id=-1 Violation Description (String);
  optional binary field_id=-1 No Standing or Stopping Violation (String);
  optional binary field_id=-1 Hydrant Violation (String);
  optional binary field_id=-1 Double Parking Violation (String);
  optional double field_id=-1 Latitude;
  optional double field_id=-1 Longitude;
  optional double field_id=-1 Community Board;
  optional double field_id=-1 Community Council ;
  optional double field_id=-1 Census Tract;
  optional double field_id=-1 BIN;
  optional double field_id=-1 BBL;
  optional double field_id=-1 NTA;
}

  Issue Date Vehicle Make
0 2014-10-01        CHEVR
1 2015-03-06        FRUEH
2 2014-07-28        SUBAR
3 2015-04-13        LEXUS
4 2015-05-19        CHRYS

Vehicle Make
ACURA     26068
AUDI      16892
BMW       45932
BUICK      5620
CADIL     12310
CHEVR    103546
CHRYS     25271
DODGE     47542
FIAT       1636
FORD     176314
FREIG      1523
FRUEH     48399
GMC       40340
HINO      11135
HONDA    130974
HYUND     32168
INFIN     20387
INTER     40393
ISUZU     16045
JAGUA      2186
JEEP      36725
KENWO      3991
KIA       11859
LEXUS     30743
LINCO     17828
MACK       3799
MAZDA     14098
ME/BE     47436
MERCU     10533
MI/F       1239
MINI       3025
MITSU     16302
NISSA    107729
NS/OT     19613
OLDSM      1086
PETER      4486
PONTI      3719
PORSC      2876
ROVER      8316
SAAB       1753
SATUR      3478
SMART      2038
STERL      1391
SUBAR     16251
SUZUK      1175
TOYOT    145664
UD         1889
UTIL       1361
VOLKS     25371
VOLVO     10697
WORK       1209
WORKH      6243
dtype: int64

### Parking Violations - Query Parquet (PyArrow)

In [29]:
from datetime import datetime

import pandas as pd

file_location = "files/Parking_Violations_Issued_-_Fiscal_Year_2015.parquet"

start_dt = datetime(2015, 1, 1)
end_dt = datetime(2015, 2, 1)
df = pd.read_parquet(
    file_location,
    engine="pyarrow",
    columns=["Issue Date", "Vehicle Make"],
    filters=[[("Issue Date", ">=", start_dt), ("Issue Date", "<", end_dt)]],
)

print(df.head())

### GET TOTAL VIOLATIONS BY VEHICLE MAKE FOR MONTH OF JANUARY ###

# Group by 'Vehicle Make' and count tickets
ticket_counts = df.groupby("Vehicle Make").size()

# Drop counts less than 100 (assuming this is bogus data)
ticket_counts = ticket_counts[ticket_counts >= 1000]

# The result is a Series with 'Vehicle Make' as the index and ticket counts as the values
ticket_counts

  Issue Date Vehicle Make
0 2015-01-20        LEXUS
1 2015-01-20        LEXUS
2 2015-01-21        TOYOT
3 2015-01-24        NISSA
4 2015-01-24        NISSA

Vehicle Make
ACURA     26068
AUDI      16892
BMW       45932
BUICK      5620
CADIL     12310
CHEVR    103546
CHRYS     25271
DODGE     47542
FIAT       1636
FORD     176314
FREIG      1523
FRUEH     48399
GMC       40340
HINO      11135
HONDA    130974
HYUND     32168
INFIN     20387
INTER     40393
ISUZU     16045
JAGUA      2186
JEEP      36725
KENWO      3991
KIA       11859
LEXUS     30743
LINCO     17828
MACK       3799
MAZDA     14098
ME/BE     47436
MERCU     10533
MI/F       1239
MINI       3025
MITSU     16302
NISSA    107729
NS/OT     19613
OLDSM      1086
PETER      4486
PONTI      3719
PORSC      2876
ROVER      8316
SAAB       1753
SATUR      3478
SMART      2038
STERL      1391
SUBAR     16251
SUZUK      1175
TOYOT    145664
UD         1889
UTIL       1361
VOLKS     25371
VOLVO     10697
WORK       1209
WORKH      6243
dtype: int64

## Apache ORC

## Convert To ORC using Pandas

In [16]:
import pandas as pd

df = pd.read_csv("files/equities.csv")

print(df.head())

df.to_orc("files/equities.orc")

df

      symbol                              name  \
0  000002.SZ             China Vanke Co., Ltd.
1  000004.SZ                               two
2  000005.SZ     Shenzhen Fountain Corporation
3  000006.SZ  Shenzhen Zhenye (Group) Co.,Ltd.
4  000007.SZ     Shenzhen Quanxinhao Co., Ltd.

                                             summary currency  \
0  China Vanke Co., Ltd., together with its subsi...      CNY
1  two is a blank check company. The company was ...      CNY
2  Shenzhen Fountain Corporation engages in real ...      CNY
3  Shenzhen Zhenye (Group) Co.,Ltd. engages in th...      CNY
4  Shenzhen Quanxinhao Co., Ltd. owns and operate...      CNY

                   sector          industry_group  \
0             Real Estate             Real Estate
1              Financials  Diversified Financials
2             Real Estate             Real Estate
3             Real Estate             Real Estate
4  Consumer Discretionary       Consumer Services

                               industry exchange                   market  \
0  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
1        Diversified Financial Services      SHZ  Shenzhen Stock Exchange
2  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
3  Real Estate Management & Development      SHZ  Shenzhen Stock Exchange
4         Hotels, Restaurants & Leisure      SHZ  Shenzhen Stock Exchange

         country state           city zipcode                     website  \
0          China   NaN       Shenzhen  518083        http://www.vanke.com
1  United States    CA  San Francisco   94129      http://www.sz000004.cn
2          China   NaN       Shenzhen  518001  http://www.fountain.com.cn
3          China   NaN       Shenzhen  518008       http://www.zhenye.com
4          China   NaN       Shenzhen  518031     http://www.sz000007.com

  market_cap          isin cusip figi composite_figi shareclass_figi
0  Large Cap  CNE100001SR9   NaN  NaN            NaN             NaN
1  Micro Cap           NaN   NaN  NaN            NaN             NaN
2  Small Cap  CNE0000001L7   NaN  NaN            NaN             NaN
3  Small Cap  CNE000000164   NaN  NaN            NaN             NaN
4  Micro Cap  CNE0000000P0   NaN  NaN            NaN             NaN

,symbol,name,summary,currency,sector,industry_group,industry,exchange,market,country,state,city,zipcode,website,market_cap,isin,cusip,figi,composite_figi,shareclass_figi
0,000002.SZ,"China Vanke Co., Ltd.","China Vanke Co., Ltd., together with its subsi...",CNY,Real Estate,Real Estate,Real Estate Management & Development,SHZ,Shenzhen Stock Exchange,China,NaN,Shenzhen,518083,http://www.vanke.com,Large Cap,CNE100001SR9,NaN,NaN,NaN,NaN
1,000004.SZ,two,two is a blank check company. The company was ...,CNY,Financials,Diversified Financials,Diversified Financial Services,SHZ,Shenzhen Stock Exchange,United States,CA,San Francisco,94129,http://www.sz000004.cn,Micro Cap,NaN,NaN,NaN,NaN,NaN
2,000005.SZ,Shenzhen Fountain Corporation,Shenzhen Fountain Corporation engages in real ...,CNY,Real Estate,Real Estate,Real Estate Management & Development,SHZ,Shenzhen Stock Exchange,China,NaN,Shenzhen,518001,http://www.fountain.com.cn,Small Cap,CNE0000001L7,NaN,NaN,NaN,NaN
3,000006.SZ,"Shenzhen Zhenye (Group) Co.,Ltd.","Shenzhen Zhenye (Group) Co.,Ltd. engages in th...",CNY,Real Estate,Real Estate,Real Estate Management & Development,SHZ,Shenzhen Stock Exchange,China,NaN,Shenzhen,518008,http://www.zhenye.com,Small Cap,CNE000000164,NaN,NaN,NaN,NaN
4,000007.SZ,"Shenzhen Quanxinhao Co., Ltd.","Shenzhen Quanxinhao Co., Ltd. owns and operate...",CNY,Consumer Discretionary,Consumer Services,"Hotels, Restaurants & Leisure",SHZ,Shenzhen Stock Exchange,China,NaN,Shenzhen,518031,http://www.sz000007.com,Micro Cap,CNE0000000P0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158642,ZZMS.SG,Commerzbank AG,Commerzbank AG provides banking and capital ma...,EUR,Financials,Banks,Banks,STU,Stuttgart Stock Exchange,Germany,NaN,Frankfurt am Main,60311,http://www.commerzbank.com,Mid Cap,NaN,NaN,NaN,NaN,NaN
158643,ZZVA.BE,NaN,NaN,EUR,NaN,NaN,NaN,BER,Berlin Stock Exchange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158644,ZZVA.DU,NaN,NaN,EUR,NaN,NaN,NaN,DUS,Dusseldorf Stock Exchange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158645,ZZZ.TO,Sleep Country Canada Holdings Inc.,"Sleep Country Canada Holdings Inc., together w...",CAD,Consumer Discretionary,Retailing,Specialty Retail,TOR,TSX Toronto Exchange,Canada,ON,Brampton,L6T 4N8,http://www.sleepcountry.ca,Small Cap,NaN,NaN,NaN,NaN,NaN
158646,ZZZOF,one,one does not have significant operations. It i...,USD,Financials,Diversified Financials,Diversified Financial Services,PNK,OTC Bulletin Board,United States,CA,San Francisco,94129,http://www.a-star.co,Small Cap,NaN,NaN,NaN,NaN,NaN

### Read Orc Using Pandas

In [30]:
import pandas as pd

df = pd.read_orc(
    "files/equities.orc", columns=["symbol", "name", "currency", "exchange"]
)

df

           symbol                                name currency exchange
0       000002.SZ               China Vanke Co., Ltd.      CNY      SHZ
1       000004.SZ                                 two      CNY      SHZ
2       000005.SZ       Shenzhen Fountain Corporation      CNY      SHZ
3       000006.SZ    Shenzhen Zhenye (Group) Co.,Ltd.      CNY      SHZ
4       000007.SZ       Shenzhen Quanxinhao Co., Ltd.      CNY      SHZ
...           ...                                 ...      ...      ...
158642    ZZMS.SG                      Commerzbank AG      EUR      STU
158643    ZZVA.BE                                None      EUR      BER
158644    ZZVA.DU                                None      EUR      DUS
158645     ZZZ.TO  Sleep Country Canada Holdings Inc.      CAD      TOR
158646      ZZZOF                                 one      USD      PNK

[158647 rows x 4 columns]

## Avro

### Convert to Avro

In [23]:
import json

from fastavro import writer, parse_schema

with open("avro/countries-schema.avsc", "r") as schema_file:
    countries_schema = json.load(schema_file)
    parsed_schema = parse_schema(countries_schema)

with open("files/countries-worldbank.json", "r") as countries_file:
    countries_data = json.load(countries_file)

with open("files/countries-worldbank.avro", "wb") as countries_avro:
    writer(countries_avro, parsed_schema, countries_data)


### Read Avro File

In [24]:
from fastavro import reader

with open("files/countries-worldbank.avro", "rb") as f:
    for country in reader(f):
        print(country)

{'id': 'ABW', 'iso2Code': 'AW', 'name': 'Aruba', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Oranjestad', 'longitude': '-70.0167', 'latitude': '12.5167'}
{'id': 'AFE', 'iso2Code': 'ZH', 'name': 'Africa Eastern and Southern', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'AFG', 'iso2Code': 'AF', 'name': 'Afghanistan', 'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Kabul', 'longitude': '69.1761', 'latitude': '34.5228'}
{'id': 'AFR', 'iso2Code': 'A9', 'name': 'Africa', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'AFW', 'iso2Code': 'ZI', 'name': 'Africa Western and Central', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'AGO', 'iso2Code': 'AO', 'name': 'Angola', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Luanda', 'longitude': '13.242', 'latitude': '-8.81155'}
{'id': 'ALB', 'iso2Code': 'AL', 'name': 'Albania', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Tirane', 'longitude': '19.8172', 'latitude': '41.3317'}
{'id': 'AND', 'iso2Code': 'AD', 'name': 'Andorra', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Andorra la Vella', 'longitude': '1.5218', 'latitude': '42.5075'}
{'id': 'ARB', 'iso2Code': '1A', 'name': 'Arab World', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'ARE', 'iso2Code': 'AE', 'name': 'United Arab Emirates', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East & North Africa'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Abu Dhabi', 'longitude': '54.3705', 'latitude': '24.4764'}
{'id': 'ARG', 'iso2Code': 'AR', 'name': 'Argentina', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': 'LAC', 'iso2code': 'XJ', 'value': 'Latin America & Caribbean (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Buenos Aires', 'longitude': '-58.4173', 'latitude': '-34.6118'}
{'id': 'ARM', 'iso2Code': 'AM', 'name': 'Armenia', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Yerevan', 'longitude': '44.509', 'latitude': '40.1596'}
{'id': 'ASM', 'iso2Code': 'AS', 'name': 'American Samoa', 'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Pago Pago', 'longitude': '-170.691', 'latitude': '-14.2846'}
{'id': 'ATG', 'iso2Code': 'AG', 'name': 'Antigua and Barbuda', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': "Saint John's", 'longitude': '-61.8456', 'latitude': '17.1175'}
{'id': 'AUS', 'iso2Code': 'AU', 'name': 'Australia', 'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Canberra', 'longitude': '149.129', 'latitude': '-35.282'}
{'id': 'AUT', 'iso2Code': 'AT', 'name': 'Austria', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Vienna', 'longitude': '16.3798', 'latitude': '48.2201'}
{'id': 'AZE', 'iso2Code': 'AZ', 'name': 'Azerbaijan', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Baku', 'longitude': '49.8932', 'latitude': '40.3834'}
{'id': 'BDI', 'iso2Code': 'BI', 'name': 'Burundi', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Bujumbura', 'longitude': '29.3639', 'latitude': '-3.3784'}
{'id': 'BEA', 'iso2Code': 'B4', 'name': 'East Asia & Pacific (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'BEC', 'iso2Code': 'B7', 'name': 'Europe & Central Asia (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'BEL', 'iso2Code': 'BE', 'name': 'Belgium', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Brussels', 'longitude': '4.36761', 'latitude': '50.8371'}
{'id': 'BEN', 'iso2Code': 'BJ', 'name': 'Benin', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Porto-Novo', 'longitude': '2.6323', 'latitude': '6.4779'}
{'id': 'BFA', 'iso2Code': 'BF', 'name': 'Burkina Faso', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Ouagadougou', 'longitude': '-1.53395', 'latitude': '12.3605'}
{'id': 'BGD', 'iso2Code': 'BD', 'name': 'Bangladesh', 'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Dhaka', 'longitude': '90.4113', 'latitude': '23.7055'}
{'id': 'BGR', 'iso2Code': 'BG', 'name': 'Bulgaria', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Sofia', 'longitude': '23.3238', 'latitude': '42.7105'}
{'id': 'BHI', 'iso2Code': 'B1', 'name': 'IBRD countries classified as high income', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}
{'id': 'BHR', 'iso2Code': 'BH', 'name': 'Bahrain', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East & North Africa'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Manama', 'longitude': '50.5354', 'latitude': '26.1921'}
{'id': 'BHS', 'iso2Code': 'BS', 'name': 'Bahamas, The', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Nassau', 'longitude': '-77.339', 'latitude': '25.0661'}
{'id': 'BIH', 'iso2Code': 'BA', 'name': 'Bosnia and Herzegovina', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Sarajevo', 'longitude': '18.4214', 'latitude': '43.8607'}
{'id': 'BLA', 'iso2Code': 'B2', 'name': 'Latin America & the Caribbean (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}

### Validate Avro

In [32]:
import json

from fastavro.validation import validate_many

with open("avro/countries-schema.avsc", "r") as schema_file:
    countries_schema = json.load(schema_file)

with open("files/countries-worldbank.json", "r") as countries_file:
    countries_data = json.load(countries_file)

validate_many(countries_data, countries_schema)

# test schema with invalid data
invalid_data = [{"id": "1", "b": 2, "c": 3}, {"id": "2", "b": 2, "c": 3}]

# fastavro._validate_common.ValidationError
validate_many(invalid_data, countries_schema)

ValidationError: [
  "Field(com.example.Country.iso2Code) is None expected string",
  "Field(com.example.Country.iso2Code) is None expected string"
]